# Travis-CI Build for libgit2
# see travis-ci.org for details

language: c




matrix:
 include:
   - compiler: i586-mingw32msvc-gcc
     env: OPTIONS="-DBUILD_CLAR=OFF -DENABLE_TRACE=ON -DWIN32=ON -DMINGW=ON -DUSE_SSH=OFF"


install:
  - ./script/install-deps-${TRAVIS_OS_NAME}.sh

# Run the Build script and tests
script:
 - script/cibuild.sh

# Run Tests
after_success:
 - if [ "$TRAVIS_OS_NAME" = "linux" -a -n "$VALGRIND" ]; then sudo apt-get -qq install valgrind; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" -a -n "$VALGRIND" ]; then valgrind --leak-check=full --show-reachable=yes --suppressions=./libgit2_clar.supp _build/libgit2_clar -ionline; fi

